### ISSUE TITLE
Additional backend database support

### ISSUE THREAD

**Issue by michaelmior** [mephux/envdb#11]
Is there any WIP to allow Envdb to use something other than sqlite? I'd love to be able to use Postgres so I could throw this up on Heroku. From the looks of things, since you're using xorm this should be pretty easy and mostly just a matter of some configuration changes. I might be able to work on a PR if this isn't already happening.

**Comment by mephux** [comment]
@michaelmior Yea, shouldn't be hard to add at all. You could create a config file or cli options to control it. Just curious, why doesn't it run on Heroku? The sqlite stuff is statically built into the envdb binary or do you just want something with a little more power?

**Comment by michaelmior** [comment]
It might run on Heroku, but you can't count on Heroku to preserve anything which is stored in the filesystem. I realized this probably won't work on Heroku anyway though because AFAICT, it requires two ports. Is this true? Unfortunately, Heroku only gives you one.

**Comment by michaelmior** [comment]
That said, you could probably still run on Heroku. It would just require to separate applications.
