### ISSUE TITLE
can't load package: package _/home/dan/envdb: cannot find package "_/home/dan/envdb" in any of:

### ISSUE THREAD

**Issue by secrettriangle** [mephux/envdb#7]
$ make
	==> Embedding Assets
	==> Installing dependencies
	can't load package: package _/home/dan/envdb: cannot find package "_/home/dan/envdb" in any of:
		/usr/lib/go/src/pkg/_/home/dan/envdb (from $GOROOT)
		/home/dan/envdb/Godeps/_workspace/src/_/home/dan/envdb (from $GOPATH)
		/home/dan/stuff/src/_/home/dan/envdb
	godep: go exit status 1
	godep: exit status 1
	make: *** [deps] Error 1

	$ echo $GOROOT x $GOPATH
	x /home/dan/stuff

**Comment by mephux** [comment]
@secrettriangle odd, It should be using godep to set the GOPATH to the GoDeps dir in the main.

try doing `go get github.com/mephux/envdb` and then making again.

**Comment by secrettriangle** [comment]
$ go get github.com/mephux/envdb
    # github.com/mephux/envdb
    stuff/src/github.com/mephux/envdb/http-handle.go:44: undefined: Asset
    stuff/src/github.com/mephux/envdb/http.go:149: undefined: Asset
    stuff/src/github.com/mephux/envdb/http.go:150: undefined: AssetDir

**Comment by mephux** [comment]
Oh, crap - forgot a dep in the readme. `go get github.com/elazarl/go-bindata-assetfs` then go get envdb again. Sorry.

**Comment by secrettriangle** [comment]
Hmm... same exact error?

**Comment by mephux** [comment]
@secrettriangle try just doing `godep go build -o bin/envdb`

**Comment by mephux** [comment]
@secrettriangle let me know if that worked. Going to close for now.

**Comment by secrettriangle** [comment]
$ godep go build -o bin/envdb
    go build _/home/dan/envdb: signal: killed
    godep: go exit status 1

**Comment by mephux** [comment]
@secrettriangle yea, I think there is something wrong with your gopath. Trying to figure out why it's looking in `_/home/dan`
