### ISSUE TITLE
Building on OS X

### ISSUE THREAD

**Issue by mojotalantikite** [mephux/envdb#8]
I'm starting to play around with envdb but ran into a couple errors while compiling for OS X 10.10.3.

The main one is that -ldflags "-s" throws a deprecation error:
```
==> Embedding Assets
==> Building envdb
# _/Users/mojo/scratch/envdb
ld: warning: option -s is obsolete and being ignored
```

The resulting envdb binary then threw an error when trying to run it:
```
~/scratch/envdb/bin master! $ ./envdb 
Bus error: 10
```

Removing the -ldflags from the Makefile worked for me.

A minor error is that the version of grep that OS X ships with doesn't have a Perl regex mode, so the -P throws a usage warning in your grep for Version:

```
==> Embedding Assets
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
```

Other than that everything is looking good so far -- thanks!

**Comment by mephux** [comment]
@mojotalantikite thanks for reporting this. Will have them both fixed shortly.

**Comment by mephux** [comment]
@mojotalantikite fixed, thanks.
